name: Run Katalon Test Suite (Headless)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-katalon-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Katalon requires Java 8 or later

      - name: Install Google Chrome (for headless testing)
        run: |
          sudo apt update
          sudo apt install -y wget
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable xvfb  # Install Xvfb

      - name: Install Katalon Runtime Engine (KRE)
        run: |
          wget -O katalon.tar.gz https://download.katalon.com/10.1.1/Katalon_Studio_Engine_Linux_64-10.1.1.tar.gz
          mkdir katalon && tar -xzf katalon.tar.gz -C katalon --strip-components=1
          chmod +x katalon/katalonc

      - name: Start Xvfb
        run: |
          Xvfb :99 -ac &  # Start Xvfb on display :99

      - name: Run Katalon Test Suite (Headless)
        run: |
          DISPLAY=:99 katalon/katalonc -noSplash \
                           -runMode=console \
                           -projectPath="$(pwd)/YourProjectPath" \
                           -retry=0 \
                           -testSuitePath="Test Suites/YourTestSuite" \
                           -browserType="ChromeHeadless" \
                           -apiKey=2136096c-4054-4784-aaec-416e2e15543f

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: katalon-reports
          path: YourProjectPath/Reports/  # Adjust to point to your reports directory
